const WordTypes = {
  VERB_ICHIDAN: "VERB_ICHIDAN",
  VERB_GODAN: "VERB_GODAN",
  VERB_PAST: "VERB_PAST",
  ADJECTIVE_KEIYOUSHI: "ADJECTIVE_KEIYOUSHI",
  ADJECTIVE_KEIYOUDOUSHI: "ADJECTIVE_KEIYOUDOUSHI"
}

export default WordTypes